import type { FootballSetup, GameDefinition, GameSignals, TeamDefinition } from './types'
import { englishEmojiPuzzles, englishGames, englishQuestions, englishWordPuzzles } from './englishData'
import { isEnglish } from './locale'

const gamesTr: GameDefinition[] = [
  {
    id: 'football',
    name: 'Halı Saha Arenası',
    shortName: 'Halı Saha',
    description: 'İki takım, canlı skor ve yorum gücü',
    commandHint: 'Seçilen takımların komutları',
    accent: '#8cff45',
    duration: 24,
  },
  {
    id: 'quiz',
    name: 'Bilgi Düellosu',
    shortName: 'Bilgi Yarışması',
    description: 'Sorular, geri sayım ve gerçek cevap oranları',
    commandHint: 'A, B, C veya D',
    accent: '#b67cff',
    duration: 20,
  },
  {
    id: 'wheel',
    name: 'Dünya Çarkı',
    shortName: 'Ülke Çarkı',
    description: 'Yorumlarla ülke oylaması ve çark seçimi',
    commandHint: 'Bir ülke adı yaz',
    accent: '#ffbd4a',
    duration: 18,
  },
  {
    id: 'emoji',
    name: 'Emoji Şifresi',
    shortName: 'Emoji Bil',
    description: 'Emojilerden kelimeyi ilk tahmin eden kazanır',
    commandHint: 'Tahminini doğrudan yaz',
    accent: '#4de8d3',
    duration: 22,
  },
  {
    id: 'word',
    name: 'Kelime Avı',
    shortName: 'Kelime Avı',
    description: 'Karışık harflerden doğru kelimeyi bul',
    commandHint: 'Kelimeyi doğrudan yaz',
    accent: '#ff7fa7',
    duration: 22,
  },
  {
    id: 'numbers',
    name: 'Sayı Kapışması',
    shortName: 'Sayı Kapışması',
    description: 'Sohbet iki seçenekten birini zirveye taşır',
    commandHint: '1 veya 2 yaz',
    accent: '#62a6ff',
    duration: 18,
  },
  {
    id: 'pickaxe',
    name: 'Düşen Kazma Madeni',
    shortName: 'Falling Pickaxe',
    description: 'Yorumlarla yönlenen kazma, bloklar, cevherler ve TNT zinciri',
    commandHint: 'tnt · hızlı/yavaş · büyük · tahta/taş/demir/altın/elmas/netherite',
    accent: '#36e3ff',
    duration: 30,
  },
  {
    id: 'raid',
    name: 'Topluluk Raid’i',
    shortName: 'Boss Raid',
    description: 'Bütün izleyiciler aynı boss’a karşı birleşir',
    commandHint: 'vur saldır · iyileş can doldur',
    accent: '#ff6b5e',
    duration: 30,
  },
  {
    id: 'tetris',
    name: 'Topluluk Tetris',
    shortName: 'Tetris',
    description: 'Sohbet aynı parçayı yönlendirir ve satırları birlikte temizler',
    commandHint: 'sol · sağ · döndür · indir',
    accent: '#45e8ff',
    duration: 30,
  },
]

export const games: GameDefinition[] = isEnglish ? englishGames : gamesTr

const questionsTr = [
  { category: 'Coğrafya', question: 'Dünyanın yüzölçümü bakımından en büyük ülkesi hangisidir?', answers: ['Kanada', 'Çin', 'Rusya', 'ABD'], correct: 2 },
  { category: 'Bilim', question: 'Işığın boşluktaki hızı yaklaşık kaç km/s’dir?', answers: ['30 bin', '150 bin', '300 bin', '1 milyon'], correct: 2 },
  { category: 'Spor', question: 'Bir futbol takımı sahaya kaç oyuncuyla çıkar?', answers: ['9', '10', '11', '12'], correct: 2 },
  { category: 'Tarih', question: 'Türkiye Büyük Millet Meclisi hangi yılda açılmıştır?', answers: ['1919', '1920', '1921', '1923'], correct: 1 },
  { category: 'Kültür', question: 'Mona Lisa tablosunun ressamı kimdir?', answers: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correct: 1 },
  { category: 'Teknoloji', question: 'WWW kısaltmasındaki ikinci W hangi kelimedir?', answers: ['Web', 'World', 'Wide', 'Wire'], correct: 2 },
  { category: 'Coğrafya', question: 'Nil Nehri hangi kıtadadır?', answers: ['Asya', 'Afrika', 'Avrupa', 'Güney Amerika'], correct: 1 },
  { category: 'Coğrafya', question: 'Japonya’nın başkenti hangisidir?', answers: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], correct: 2 },
  { category: 'Coğrafya', question: 'Türkiye’nin en büyük gölü hangisidir?', answers: ['Tuz Gölü', 'Beyşehir Gölü', 'Van Gölü', 'Eğirdir Gölü'], correct: 2 },
  { category: 'Coğrafya', question: 'Amazon Ormanları ağırlıklı olarak hangi ülkededir?', answers: ['Peru', 'Brezilya', 'Kolombiya', 'Bolivya'], correct: 1 },
  { category: 'Bilim', question: 'Suyun kimyasal formülü hangisidir?', answers: ['CO₂', 'H₂O', 'O₂', 'NaCl'], correct: 1 },
  { category: 'Bilim', question: 'Dünya’nın doğal uydusunun adı nedir?', answers: ['Mars', 'Venüs', 'Ay', 'Titan'], correct: 2 },
  { category: 'Bilim', question: 'İnsan vücudundaki en büyük organ hangisidir?', answers: ['Kalp', 'Karaciğer', 'Akciğer', 'Deri'], correct: 3 },
  { category: 'Bilim', question: 'Bitkilerin ışıkla besin üretmesine ne denir?', answers: ['Solunum', 'Fotosentez', 'Fermantasyon', 'Buharlaşma'], correct: 1 },
  { category: 'Spor', question: 'Basketbolda serbest atış kaç sayıdır?', answers: ['1', '2', '3', '4'], correct: 0 },
  { category: 'Spor', question: 'Voleybol sahasında bir takım kaç oyuncuyla yer alır?', answers: ['5', '6', '7', '8'], correct: 1 },
  { category: 'Spor', question: 'Teniste sıfır puan nasıl ifade edilir?', answers: ['Zero', 'Love', 'Blank', 'Nil'], correct: 1 },
  { category: 'Spor', question: 'Olimpiyat halkalarının sayısı kaçtır?', answers: ['4', '5', '6', '7'], correct: 1 },
  { category: 'Tarih', question: 'İstanbul’un fethi hangi yılda gerçekleşmiştir?', answers: ['1451', '1453', '1461', '1473'], correct: 1 },
  { category: 'Tarih', question: 'Türkiye Cumhuriyeti hangi yılda ilan edilmiştir?', answers: ['1919', '1920', '1922', '1923'], correct: 3 },
  { category: 'Tarih', question: 'Matbaayı Avrupa’da geliştiren kişi kimdir?', answers: ['Edison', 'Gutenberg', 'Tesla', 'Bell'], correct: 1 },
  { category: 'Tarih', question: 'Antik Olimpiyatlar hangi ülkede başlamıştır?', answers: ['İtalya', 'Mısır', 'Yunanistan', 'İspanya'], correct: 2 },
  { category: 'Kültür', question: 'Küçük Prens kitabının yazarı kimdir?', answers: ['Victor Hugo', 'Jules Verne', 'Antoine de Saint-Exupéry', 'Albert Camus'], correct: 2 },
  { category: 'Kültür', question: 'Bir orkestrayı yöneten kişiye ne denir?', answers: ['Solist', 'Besteci', 'Şef', 'Tenor'], correct: 2 },
  { category: 'Kültür', question: 'Hamlet eserinin yazarı kimdir?', answers: ['Shakespeare', 'Dante', 'Goethe', 'Tolstoy'], correct: 0 },
  { category: 'Kültür', question: 'Sinemada görüntüyü kaydeden cihaza ne denir?', answers: ['Projektör', 'Kamera', 'Mikser', 'Monitör'], correct: 1 },
  { category: 'Teknoloji', question: 'CPU’nun Türkçe karşılığı hangisidir?', answers: ['Ekran kartı', 'Merkezi işlem birimi', 'Bellek', 'Sabit disk'], correct: 1 },
  { category: 'Teknoloji', question: 'HTML temel olarak ne oluşturmak için kullanılır?', answers: ['Web sayfası', 'Video', 'Ses dosyası', 'Veritabanı'], correct: 0 },
  { category: 'Teknoloji', question: 'Bir bayt kaç bitten oluşur?', answers: ['4', '8', '16', '32'], correct: 1 },
  { category: 'Teknoloji', question: 'İki aşamalı doğrulamanın amacı nedir?', answers: ['Hızı artırmak', 'Güvenliği artırmak', 'Dosya küçültmek', 'Ekranı büyütmek'], correct: 1 },
  { category: 'Coğrafya', question: 'Avustralya’nın başkenti hangisidir?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Perth'], correct: 2 },
  { category: 'Coğrafya', question: 'Dünyanın en büyük okyanusu hangisidir?', answers: ['Atlas', 'Hint', 'Arktik', 'Pasifik'], correct: 3 },
  { category: 'Coğrafya', question: 'Tuna Nehri hangi kıtadadır?', answers: ['Avrupa', 'Asya', 'Afrika', 'Kuzey Amerika'], correct: 0 },
  { category: 'Coğrafya', question: 'Sahra Çölü hangi kıtada bulunur?', answers: ['Asya', 'Afrika', 'Avustralya', 'Güney Amerika'], correct: 1 },
  { category: 'Coğrafya', question: 'Kanada’nın başkenti hangisidir?', answers: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], correct: 2 },
  { category: 'Coğrafya', question: 'İstanbul’da Avrupa ile Asya’yı ayıran boğaz hangisidir?', answers: ['Çanakkale', 'Cebelitarık', 'İstanbul', 'Bering'], correct: 2 },
  { category: 'Coğrafya', question: 'Paris şehrinden geçen nehir hangisidir?', answers: ['Ren', 'Sen', 'Tuna', 'Volga'], correct: 1 },
  { category: 'Coğrafya', question: 'Arjantin’in başkenti hangisidir?', answers: ['Lima', 'Santiago', 'Buenos Aires', 'Montevideo'], correct: 2 },
  { category: 'Coğrafya', question: 'Yüzölçümü bakımından en küçük kıta hangisidir?', answers: ['Avrupa', 'Avustralya', 'Antarktika', 'Güney Amerika'], correct: 1 },
  { category: 'Coğrafya', question: 'Türkiye sınırları içindeki en uzun nehir hangisidir?', answers: ['Fırat', 'Sakarya', 'Kızılırmak', 'Dicle'], correct: 2 },
  { category: 'Bilim', question: 'Güneş Sistemi’nin kırmızı gezegeni hangisidir?', answers: ['Venüs', 'Mars', 'Jüpiter', 'Merkür'], correct: 1 },
  { category: 'Bilim', question: 'Bitkiler fotosentez sırasında hangi gazı kullanır?', answers: ['Oksijen', 'Azot', 'Karbondioksit', 'Hidrojen'], correct: 2 },
  { category: 'Bilim', question: 'Atomun merkezinde bulunan bölüme ne denir?', answers: ['Yörünge', 'Çekirdek', 'Elektron', 'Katman'], correct: 1 },
  { category: 'Bilim', question: 'Su deniz seviyesinde kaç santigrat derecede kaynar?', answers: ['80', '90', '100', '120'], correct: 2 },
  { category: 'Bilim', question: 'Kuvvetin SI birimi hangisidir?', answers: ['Joule', 'Watt', 'Pascal', 'Newton'], correct: 3 },
  { category: 'Bilim', question: 'Yetişkin bir insan iskeletinde yaklaşık kaç kemik bulunur?', answers: ['106', '206', '306', '406'], correct: 1 },
  { category: 'Bilim', question: 'Dünya’ya en yakın yıldız hangisidir?', answers: ['Sirius', 'Kutup Yıldızı', 'Güneş', 'Proxima Centauri'], correct: 2 },
  { category: 'Bilim', question: 'Nötr bir çözeltinin pH değeri kaçtır?', answers: ['0', '5', '7', '14'], correct: 2 },
  { category: 'Bilim', question: 'Kana kırmızı rengini veren protein hangisidir?', answers: ['Keratin', 'Hemoglobin', 'Kolajen', 'İnsülin'], correct: 1 },
  { category: 'Bilim', question: 'DNA kısaltmasındaki D harfi hangi kelimeyi temsil eder?', answers: ['Dinamik', 'Deoksiribo', 'Dijital', 'Doğal'], correct: 1 },
  { category: 'Tarih', question: 'Magna Carta hangi ülkede imzalanmıştır?', answers: ['Fransa', 'İngiltere', 'İspanya', 'İtalya'], correct: 1 },
  { category: 'Tarih', question: 'Fransız Devrimi hangi yılda başlamıştır?', answers: ['1689', '1789', '1889', '1919'], correct: 1 },
  { category: 'Tarih', question: 'Ay’a ayak basan ilk insan kimdir?', answers: ['Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn'], correct: 2 },
  { category: 'Tarih', question: 'Yazıyı ilk kullanan uygarlıklardan biri hangisidir?', answers: ['Sümerler', 'Vikingler', 'Aztekler', 'Romalılar'], correct: 0 },
  { category: 'Tarih', question: 'Roma İmparatorluğu’nun ilk merkezi hangi şehirdi?', answers: ['Atina', 'Roma', 'Paris', 'Kartaca'], correct: 1 },
  { category: 'Tarih', question: 'İkinci Dünya Savaşı hangi yılda sona ermiştir?', answers: ['1939', '1943', '1945', '1950'], correct: 2 },
  { category: 'Tarih', question: 'İpek Yolu tarihsel olarak Çin’i ağırlıklı olarak hangi kıtaya bağlamıştır?', answers: ['Avrupa', 'Avustralya', 'Antarktika', 'Güney Amerika'], correct: 0 },
  { category: 'Tarih', question: 'Adında “Türk” kelimesi bulunan ilk Türk devleti hangisidir?', answers: ['Hunlar', 'Göktürkler', 'Uygurlar', 'Karahanlılar'], correct: 1 },
  { category: 'Tarih', question: 'Çanakkale Savaşları hangi yıl başlamıştır?', answers: ['1914', '1915', '1916', '1918'], correct: 1 },
  { category: 'Tarih', question: 'Rönesans ilk olarak hangi ülkede güç kazanmıştır?', answers: ['İtalya', 'Almanya', 'Norveç', 'Portekiz'], correct: 0 },
  { category: 'Kültür', question: 'Yıldızlı Gece tablosunun ressamı kimdir?', answers: ['Van Gogh', 'Monet', 'Picasso', 'Rembrandt'], correct: 0 },
  { category: 'Kültür', question: 'Don Kişot romanının yazarı kimdir?', answers: ['Cervantes', 'Dostoyevski', 'Kafka', 'Hemingway'], correct: 0 },
  { category: 'Kültür', question: 'Fındıkkıran balesinin bestecisi kimdir?', answers: ['Mozart', 'Beethoven', 'Çaykovski', 'Vivaldi'], correct: 2 },
  { category: 'Kültür', question: 'Oscar ödülleri ağırlıklı olarak hangi sanat dalıyla ilgilidir?', answers: ['Resim', 'Sinema', 'Mimari', 'Heykel'], correct: 1 },
  { category: 'Kültür', question: 'Japon kâğıt katlama sanatına ne denir?', answers: ['Origami', 'Haiku', 'Kabuki', 'Manga'], correct: 0 },
  { category: 'Kültür', question: 'Temel müzik dizisinde kaç nota adı bulunur?', answers: ['5', '6', '7', '8'], correct: 2 },
  { category: 'Kültür', question: 'Karagöz ile Hacivat hangi geleneksel sanatın karakterleridir?', answers: ['Gölge oyunu', 'Opera', 'Bale', 'Pandomim'], correct: 0 },
  { category: 'Kültür', question: 'İlahi Komedya eserinin yazarı kimdir?', answers: ['Dante', 'Goethe', 'Tolstoy', 'Homeros'], correct: 0 },
  { category: 'Kültür', question: 'Guernica tablosunu kim yapmıştır?', answers: ['Salvador Dali', 'Pablo Picasso', 'Claude Monet', 'Edvard Munch'], correct: 1 },
  { category: 'Kültür', question: 'Nobel Edebiyat Ödülü hangi alandaki çalışmalara verilir?', answers: ['Mimari', 'Edebiyat', 'Spor', 'Astronomi'], correct: 1 },
  { category: 'Teknoloji', question: 'RAM belleğin temel özelliği hangisidir?', answers: ['Geçici veri tutmak', 'Kâğıda yazdırmak', 'Ses üretmek', 'İnterneti dağıtmak'], correct: 0 },
  { category: 'Teknoloji', question: 'URL neyi belirtir?', answers: ['Ekran çözünürlüğünü', 'İnternet kaynağının adresini', 'İşlemci hızını', 'Dosya boyutunu'], correct: 1 },
  { category: 'Teknoloji', question: 'İkili sayı sistemi hangi iki rakamı kullanır?', answers: ['0 ve 1', '1 ve 2', '2 ve 3', '8 ve 9'], correct: 0 },
  { category: 'Teknoloji', question: 'Linux çekirdeğini ilk geliştiren kişi kimdir?', answers: ['Bill Gates', 'Steve Jobs', 'Linus Torvalds', 'Tim Berners-Lee'], correct: 2 },
  { category: 'Teknoloji', question: 'HTTPS bağlantısındaki S harfi neyi ifade eder?', answers: ['Simple', 'Secure', 'System', 'Speed'], correct: 1 },
  { category: 'Teknoloji', question: 'GPU ağırlıklı olarak hangi işlemleri hızlandırır?', answers: ['Grafik', 'Klavye', 'Depolama', 'Yazdırma'], correct: 0 },
  { category: 'Teknoloji', question: 'QR koddaki QR harfleri hangi ifadenin kısaltmasıdır?', answers: ['Quick Response', 'Quality Read', 'Query Route', 'Quantum Record'], correct: 0 },
  { category: 'Teknoloji', question: 'Açık kaynak yazılımın ayırt edici özelliği nedir?', answers: ['Kaynak kodunun incelenebilmesi', 'İnternetsiz çalışmaması', 'Yalnızca ücretli olması', 'Sadece telefonda açılması'], correct: 0 },
  { category: 'Teknoloji', question: 'SQL ağırlıklı olarak neyle çalışmak için kullanılır?', answers: ['Veritabanları', 'Video montajı', 'Ses kaydı', 'Üç boyutlu baskı'], correct: 0 },
  { category: 'Teknoloji', question: 'Bulut bilişimde veriler çoğunlukla nerede işlenir?', answers: ['Uzak sunucularda', 'Yalnızca klavyede', 'Ekran kartı kablosunda', 'Yazıcı kartuşunda'], correct: 0 },
]

export const questions = isEnglish ? englishQuestions : questionsTr

const sovereignCountryCodes = `AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PS PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE CH SY TW TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VA VE VN YE ZM ZW XK`.split(' ')

const countryNames = new Intl.DisplayNames([isEnglish ? 'en' : 'tr'], { type: 'region' })
const countryNameOverrides: Record<string, string> = isEnglish ? {} : {
  BO: 'Bolivya', BN: 'Brunei', CD: 'Demokratik Kongo Cumhuriyeti', CG: 'Kongo Cumhuriyeti',
  CI: 'Fildişi Sahili', CV: 'Yeşil Burun Adaları', CZ: 'Çekya', GB: 'Birleşik Krallık',
  IR: 'İran', KP: 'Kuzey Kore', KR: 'Güney Kore', LA: 'Laos', MD: 'Moldova',
  PS: 'Filistin', RU: 'Rusya', SY: 'Suriye', TZ: 'Tanzanya', US: 'Amerika Birleşik Devletleri',
  VA: 'Vatikan', VE: 'Venezuela', VN: 'Vietnam', XK: 'Kosova',
}
const countryExtraAliases: Record<string, string[]> = {
  TR: ['türkiye', 'turkiye'], US: ['abd', 'amerika', 'usa'], GB: ['ingiltere', 'britanya', 'uk'],
  KR: ['güney kore', 'kore'], KP: ['kuzey kore'], AE: ['bae', 'birleşik arap emirlikleri'],
  NL: ['hollanda'], CZ: ['çek cumhuriyeti'], XK: ['kosova', 'kosovo'],
}

const flagFromCode = (code: string) => code.replace(/./g, (letter) => String.fromCodePoint(127397 + letter.charCodeAt(0)))

export const countries = sovereignCountryCodes.map((code, index) => {
  const name = countryNameOverrides[code] || countryNames.of(code) || code
  return {
    code,
    name,
    aliases: [name, code, ...(countryExtraAliases[code] || [])],
    flag: flagFromCode(code),
    color: `hsl(${(index * 137.508) % 360} 58% ${index % 2 ? 42 : 52}%)`,
  }
})

export const teams: TeamDefinition[] = [
  { id: 'galatasaray', name: 'Galatasaray', shortName: 'GS', command: 'gs', colors: ['#f6c900', '#d71920'], crest: 'GS', league: 'Türkiye' },
  { id: 'fenerbahce', name: 'Fenerbahçe', shortName: 'FB', command: 'fb', colors: ['#ffed00', '#092a5e'], crest: 'FB', league: 'Türkiye' },
  { id: 'besiktas', name: 'Beşiktaş', shortName: 'BJK', command: 'bjk', colors: ['#ffffff', '#111111'], crest: 'BJK', league: 'Türkiye' },
  { id: 'trabzonspor', name: 'Trabzonspor', shortName: 'TS', command: 'ts', colors: ['#7a263a', '#64b5e5'], crest: 'TS', league: 'Türkiye' },
  { id: 'basaksehir', name: 'Başakşehir', shortName: 'İBFK', command: 'ibfk', colors: ['#f58220', '#203e78'], crest: 'İB', league: 'Türkiye' },
  { id: 'bursaspor', name: 'Bursaspor', shortName: 'BRS', command: 'bursa', colors: ['#159447', '#ffffff'], crest: 'BS', league: 'Türkiye' },
  { id: 'real-madrid', name: 'Real Madrid', shortName: 'RMA', command: 'real', colors: ['#ffffff', '#d8b400'], crest: 'RM', league: 'İspanya' },
  { id: 'barcelona', name: 'Barcelona', shortName: 'BAR', command: 'barca', colors: ['#004d98', '#a50044'], crest: 'FCB', league: 'İspanya' },
  { id: 'liverpool', name: 'Liverpool', shortName: 'LIV', command: 'liv', colors: ['#c8102e', '#00b2a9'], crest: 'LFC', league: 'İngiltere' },
  { id: 'manchester-city', name: 'Manchester City', shortName: 'MCI', command: 'city', colors: ['#6cabdd', '#ffffff'], crest: 'MC', league: 'İngiltere' },
  { id: 'arsenal', name: 'Arsenal', shortName: 'ARS', command: 'arsenal', colors: ['#ef0107', '#ffffff'], crest: 'AFC', league: 'İngiltere' },
  { id: 'bayern', name: 'Bayern Münih', shortName: 'FCB', command: 'bayern', colors: ['#dc052d', '#0066b2'], crest: 'FCB', league: 'Almanya' },
  { id: 'psg', name: 'Paris Saint-Germain', shortName: 'PSG', command: 'psg', colors: ['#004170', '#da291c'], crest: 'PSG', league: 'Fransa' },
  { id: 'juventus', name: 'Juventus', shortName: 'JUV', command: 'juve', colors: ['#ffffff', '#111111'], crest: 'J', league: 'İtalya' },
  { id: 'milan', name: 'AC Milan', shortName: 'MIL', command: 'milan', colors: ['#fb090b', '#111111'], crest: 'ACM', league: 'İtalya' },
  { id: 'inter', name: 'Inter', shortName: 'INT', command: 'inter', colors: ['#0068a8', '#111111'], crest: 'IM', league: 'İtalya' },
  { id: 'adana-demirspor', name: 'Adana Demirspor', shortName: 'ADS', command: 'adana', colors: ['#66b9e8', '#163c74'], crest: 'ADS', league: 'Türkiye' },
  { id: 'goztepe', name: 'Göztepe', shortName: 'GÖZ', command: 'goztepe', colors: ['#e21b2d', '#f7cf18'], crest: 'GÖZ', league: 'Türkiye' },
  { id: 'samsunspor', name: 'Samsunspor', shortName: 'SAM', command: 'samsun', colors: ['#e21b23', '#ffffff'], crest: 'SAM', league: 'Türkiye' },
  { id: 'konyaspor', name: 'Konyaspor', shortName: 'KON', command: 'konya', colors: ['#159447', '#ffffff'], crest: 'KON', league: 'Türkiye' },
  { id: 'manchester-united', name: 'Manchester United', shortName: 'MUN', command: 'united', colors: ['#da291c', '#fbe122'], crest: 'MU', league: 'İngiltere' },
  { id: 'chelsea', name: 'Chelsea', shortName: 'CHE', command: 'chelsea', colors: ['#034694', '#ffffff'], crest: 'CFC', league: 'İngiltere' },
  { id: 'tottenham', name: 'Tottenham', shortName: 'TOT', command: 'spurs', colors: ['#ffffff', '#132257'], crest: 'TH', league: 'İngiltere' },
  { id: 'atletico-madrid', name: 'Atletico Madrid', shortName: 'ATM', command: 'atletico', colors: ['#cb3524', '#ffffff'], crest: 'ATM', league: 'İspanya' },
  { id: 'dortmund', name: 'Borussia Dortmund', shortName: 'BVB', command: 'bvb', colors: ['#fde100', '#111111'], crest: 'BVB', league: 'Almanya' },
  { id: 'leverkusen', name: 'Bayer Leverkusen', shortName: 'B04', command: 'bayer', colors: ['#e32221', '#111111'], crest: 'B04', league: 'Almanya' },
  { id: 'napoli', name: 'Napoli', shortName: 'NAP', command: 'napoli', colors: ['#12a0d7', '#ffffff'], crest: 'NAP', league: 'İtalya' },
  { id: 'roma', name: 'Roma', shortName: 'ROM', command: 'roma', colors: ['#8e1f2f', '#f0bc42'], crest: 'ASR', league: 'İtalya' },
  { id: 'marseille', name: 'Olympique Marseille', shortName: 'OM', command: 'marsilya', colors: ['#2faee0', '#ffffff'], crest: 'OM', league: 'Fransa' },
  { id: 'benfica', name: 'Benfica', shortName: 'SLB', command: 'benfica', colors: ['#e30613', '#ffffff'], crest: 'SLB', league: 'Portekiz' },
  { id: 'porto', name: 'Porto', shortName: 'FCP', command: 'porto', colors: ['#005ca9', '#ffffff'], crest: 'FCP', league: 'Portekiz' },
  { id: 'ajax', name: 'Ajax', shortName: 'AJX', command: 'ajax', colors: ['#d2122e', '#ffffff'], crest: 'AFC', league: 'Hollanda' },
]

export const defaultFootballSetup: FootballSetup = { home: teams[0], away: teams[1] }

const emojiPuzzlesTr = [
  { emoji: '🌈', clues: ['gök', 'renk', 'yağmur'], answer: 'gökkuşağı' },
  { emoji: '☕ ❤️', clues: ['sıcak', 'fincan', 'mola'], answer: 'kahve' },
  { emoji: '🧭 🗺️', clues: ['yol', 'keşif', 'serüven'], answer: 'macera' },
  { emoji: '🌙 ⭐', clues: ['gece', 'gökyüzü', 'ışık'], answer: 'yıldız' },
  { emoji: '⚽ 🥅', clues: ['saha', 'gol', 'takım'], answer: 'futbol' },
  { emoji: '🎬 🍿', clues: ['perde', 'film', 'salon'], answer: 'sinema' },
  { emoji: '✈️ 🧳', clues: ['uçuş', 'valiz', 'yol'], answer: 'seyahat' },
  { emoji: '📚 🎓', clues: ['okul', 'bilgi', 'ders'], answer: 'eğitim' },
  { emoji: '💻 🌐', clues: ['ağ', 'bilgisayar', 'bağlantı'], answer: 'internet' },
  { emoji: '🎤 🎶', clues: ['ses', 'sahne', 'şarkı'], answer: 'müzik' },
  { emoji: '🍕 🧀', clues: ['hamur', 'dilim', 'fırın'], answer: 'pizza' },
  { emoji: '🚲 🛣️', clues: ['pedal', 'iki teker', 'yol'], answer: 'bisiklet' },
  { emoji: '🌧️ ☂️', clues: ['yağmur', 'korunmak', 'açmak'], answer: 'şemsiye' },
  { emoji: '🐝 🍯', clues: ['arı', 'tatlı', 'kovan'], answer: 'bal' },
  { emoji: '🌋 🔥', clues: ['lav', 'dağ', 'patlama'], answer: 'volkan' },
  { emoji: '🚀 🪐', clues: ['uzay', 'yolculuk', 'gezegen'], answer: 'roket' },
  { emoji: '🏆 🎉', clues: ['birinci', 'kupa', 'zafer'], answer: 'şampiyon' },
  { emoji: '🔑 🚪', clues: ['kilit', 'kapı', 'açmak'], answer: 'anahtar' },
  { emoji: '📷 🌄', clues: ['görüntü', 'çekim', 'anı'], answer: 'fotoğraf' },
  { emoji: '🧩 🧠', clues: ['parça', 'düşünmek', 'çözmek'], answer: 'bulmaca' },
  { emoji: '🌳 🌲', clues: ['ağaç', 'doğa', 'yeşil'], answer: 'orman' },
  { emoji: '🏖️ 🌊', clues: ['kum', 'deniz', 'tatil'], answer: 'sahil' },
  { emoji: '🍰 🎂', clues: ['mum', 'kutlama', 'tatlı'], answer: 'pasta' },
  { emoji: '⏰ 🛌', clues: ['sabah', 'uyanmak', 'ses'], answer: 'alarm' },
  { emoji: '🦋 🌸', clues: ['kanat', 'çiçek', 'renk'], answer: 'kelebek' },
  { emoji: '🗺️ 📍', clues: ['konum', 'yol', 'ülke'], answer: 'harita' },
  { emoji: '🎮 🕹️', clues: ['eğlence', 'kontrol', 'ekran'], answer: 'oyun' },
  { emoji: '🧑‍🍳 🍳', clues: ['yemek', 'mutfak', 'pişirmek'], answer: 'aşçı' },
  { emoji: '📡 📺', clues: ['canlı', 'ekran', 'izleyici'], answer: 'yayın' },
  { emoji: '🤖 ⚙️', clues: ['makine', 'otomatik', 'teknoloji'], answer: 'robot' },
  { emoji: '☀️ 🌻', clues: ['sıcak', 'gökyüzü', 'ışık'], answer: 'güneş' },
  { emoji: '⛄ ❄️', clues: ['kış', 'soğuk', 'havuç'], answer: 'kardan adam' },
  { emoji: '🌊 🗼', clues: ['kıyı', 'ışık', 'gemi'], answer: 'deniz feneri' },
  { emoji: '⛺ 🔥', clues: ['doğa', 'çadır', 'gece'], answer: 'kamp' },
  { emoji: '🚒 🔥', clues: ['yangın', 'kurtarma', 'hortum'], answer: 'itfaiyeci' },
  { emoji: '🩺 👨‍⚕️', clues: ['sağlık', 'muayene', 'hastalık'], answer: 'doktor' },
  { emoji: '🦷 🪥', clues: ['diş', 'muayene', 'fırça'], answer: 'dişçi' },
  { emoji: '👮 🚓', clues: ['güvenlik', 'üniforma', 'devriye'], answer: 'polis' },
  { emoji: '🧑‍🚀 🌌', clues: ['uzay', 'kask', 'yörünge'], answer: 'astronot' },
  { emoji: '🥖 🥐', clues: ['ekmek', 'hamur', 'sıcak'], answer: 'fırın' },
  { emoji: '🍔 🍟', clues: ['köfte', 'ekmek', 'hızlı yemek'], answer: 'hamburger' },
  { emoji: '🍉 🔪', clues: ['yaz', 'meyve', 'çekirdek'], answer: 'karpuz' },
  { emoji: '🍓 🌱', clues: ['kırmızı', 'meyve', 'tatlı'], answer: 'çilek' },
  { emoji: '🍦 ❄️', clues: ['soğuk', 'tatlı', 'külah'], answer: 'dondurma' },
  { emoji: '🚆 🛤️', clues: ['ray', 'vagon', 'istasyon'], answer: 'tren' },
  { emoji: '🚢 ⚓', clues: ['deniz', 'liman', 'yolculuk'], answer: 'gemi' },
  { emoji: '🚕 💵', clues: ['şehir', 'yolcu', 'ücret'], answer: 'taksi' },
  { emoji: '🚦 🚗', clues: ['kırmızı', 'yeşil', 'yol'], answer: 'trafik' },
  { emoji: '⛰️ 🧗', clues: ['yüksek', 'tırmanış', 'zirve'], answer: 'dağ' },
  { emoji: '🏜️ 🐪', clues: ['kum', 'sıcak', 'vaha'], answer: 'çöl' },
  { emoji: '💧 🏞️', clues: ['yüksekten', 'su', 'doğa'], answer: 'şelale' },
  { emoji: '🐈 🧶', clues: ['pati', 'miyav', 'evcil'], answer: 'kedi' },
  { emoji: '🐕 🦴', clues: ['pati', 'havlama', 'sadık'], answer: 'köpek' },
  { emoji: '🐧 🧊', clues: ['kutup', 'siyah beyaz', 'kuş'], answer: 'penguen' },
  { emoji: '🦁 👑', clues: ['orman', 'yele', 'kral'], answer: 'aslan' },
  { emoji: '🐬 🌊', clues: ['deniz', 'zeki', 'yüzgeç'], answer: 'yunus' },
  { emoji: '🐙 🌊', clues: ['sekiz kol', 'deniz', 'mürekkep'], answer: 'ahtapot' },
  { emoji: '🐢 🥬', clues: ['kabuk', 'yavaş', 'uzun ömür'], answer: 'kaplumbağa' },
  { emoji: '🦉 🌙', clues: ['gece', 'kuş', 'bilge'], answer: 'baykuş' },
  { emoji: '🏀 ⛹️', clues: ['pota', 'top', 'sayı'], answer: 'basketbol' },
  { emoji: '🎾 🥎', clues: ['raket', 'kort', 'file'], answer: 'tenis' },
  { emoji: '🏊 💦', clues: ['havuz', 'su', 'kulvar'], answer: 'yüzme' },
  { emoji: '⛷️ ❄️', clues: ['kar', 'pist', 'kış sporu'], answer: 'kayak' },
  { emoji: '🥇 🏅', clues: ['başarı', 'yarış', 'ödül'], answer: 'madalya' },
  { emoji: '📅 ✏️', clues: ['tarih', 'ay', 'plan'], answer: 'takvim' },
  { emoji: '🧭 🧲', clues: ['kuzey', 'yön', 'iğne'], answer: 'pusula' },
  { emoji: '🌪️ 🏠', clues: ['rüzgâr', 'fırtına', 'dönmek'], answer: 'kasırga' },
  { emoji: '🌨️ ⛄', clues: ['beyaz', 'kış', 'yağış'], answer: 'kar' },
  { emoji: '⚡ 🌩️', clues: ['fırtına', 'ışık', 'elektrik'], answer: 'şimşek' },
  { emoji: '🌅 ☕', clues: ['sabah', 'ufuk', 'ışık'], answer: 'gün doğumu' },
  { emoji: '🌇 🌙', clues: ['akşam', 'ufuk', 'turuncu'], answer: 'gün batımı' },
  { emoji: '📱 📞', clues: ['arama', 'mesaj', 'ekran'], answer: 'telefon' },
  { emoji: '⌚ ⏱️', clues: ['zaman', 'bilek', 'dakika'], answer: 'saat' },
  { emoji: '💡 ⚡', clues: ['fikir', 'ışık', 'elektrik'], answer: 'ampul' },
  { emoji: '🧲 📎', clues: ['çekim', 'metal', 'kutuplar'], answer: 'mıknatıs' },
  { emoji: '🧪 🔬', clues: ['deney', 'bilim', 'önlük'], answer: 'laboratuvar' },
  { emoji: '🏥 🚑', clues: ['sağlık', 'doktor', 'acil'], answer: 'hastane' },
  { emoji: '📚 🤫', clues: ['kitap', 'sessizlik', 'okuma'], answer: 'kütüphane' },
  { emoji: '🛒 🧾', clues: ['alışveriş', 'raf', 'kasa'], answer: 'market' },
  { emoji: '📮 ✉️', clues: ['mektup', 'zarf', 'gönderi'], answer: 'posta' },
]

export const emojiPuzzles = isEnglish ? englishEmojiPuzzles : emojiPuzzlesTr

const wordBank = [
  { category: 'Yayın', answer: 'kamera', hint: 'Yayının görüntüsünü yakalar' },
  { category: 'Yayın', answer: 'mikrofon', hint: 'Sesi izleyiciye ulaştırır' },
  { category: 'Yayın', answer: 'izleyici', hint: 'Canlı yayının gerçek gücü' },
  { category: 'Yayın', answer: 'yayın', hint: 'İçeriğin canlı olarak aktarılması' },
  { category: 'Yayın', answer: 'sahne', hint: 'Oyunun ekranda görünen alanı' },
  { category: 'Yayın', answer: 'yorum', hint: 'İzleyicinin yazdığı mesaj' },
  { category: 'Yayın', answer: 'ekran', hint: 'Görüntülerin izlendiği yüzey' },
  { category: 'Yayın', answer: 'bağlantı', hint: 'Yayını platforma ulaştıran köprü' },
  { category: 'Yayın', answer: 'etkileşim', hint: 'İzleyiciyle kurulan canlı iletişim' },
  { category: 'Yayın', answer: 'otomasyon', hint: 'İşleri kendiliğinden yürüten sistem' },

  { category: 'Spor', answer: 'futbol', hint: 'Yeşil sahada on bir kişiyle oynanır' },
  { category: 'Spor', answer: 'basketbol', hint: 'Top çemberden geçirilerek sayı kazanılır' },
  { category: 'Spor', answer: 'voleybol', hint: 'File üzerinden ellerle oynanır' },
  { category: 'Spor', answer: 'hakem', hint: 'Maçın kurallarını uygular' },
  { category: 'Spor', answer: 'stadyum', hint: 'Büyük karşılaşmaların oynandığı yer' },
  { category: 'Spor', answer: 'şampiyon', hint: 'Sezonu zirvede tamamlayan' },
  { category: 'Spor', answer: 'tribün', hint: 'Taraftarların maçı izlediği bölüm' },
  { category: 'Spor', answer: 'kaleci', hint: 'Kaleyi koruyan oyuncu' },
  { category: 'Spor', answer: 'forma', hint: 'Takım renklerini taşıyan kıyafet' },
  { category: 'Spor', answer: 'turnuva', hint: 'Birçok rakibin kupaya ulaşmak için yarışması' },

  { category: 'Teknoloji', answer: 'bilgisayar', hint: 'Programları çalıştıran elektronik cihaz' },
  { category: 'Teknoloji', answer: 'klavye', hint: 'Yazı yazmak için kullanılan tuş takımı' },
  { category: 'Teknoloji', answer: 'internet', hint: 'Dünyayı birbirine bağlayan ağ' },
  { category: 'Teknoloji', answer: 'yazılım', hint: 'Cihaza ne yapacağını söyleyen programlar' },
  { category: 'Teknoloji', answer: 'robot', hint: 'Görevleri otomatik yapan makine' },
  { category: 'Teknoloji', answer: 'algoritma', hint: 'Bir problemi çözen sıralı adımlar' },
  { category: 'Teknoloji', answer: 'piksel', hint: 'Dijital görüntünün en küçük noktası' },
  { category: 'Teknoloji', answer: 'sunucu', hint: 'İsteklere veri sağlayan bilgisayar' },
  { category: 'Teknoloji', answer: 'tarayıcı', hint: 'İnternet sitelerini açan uygulama' },
  { category: 'Teknoloji', answer: 'kodlama', hint: 'Bilgisayara komut yazma işi' },

  { category: 'Doğa', answer: 'gökkuşağı', hint: 'Yağmurdan sonra gökyüzünde renkler oluşturur' },
  { category: 'Doğa', answer: 'okyanus', hint: 'Kıtaları çevreleyen dev su kütlesi' },
  { category: 'Doğa', answer: 'orman', hint: 'Çok sayıda ağacın yaşadığı alan' },
  { category: 'Doğa', answer: 'yıldırım', hint: 'Bulutlarla yer arasındaki güçlü elektrik' },
  { category: 'Doğa', answer: 'gezegen', hint: 'Bir yıldızın çevresinde dolanan gök cismi' },
  { category: 'Doğa', answer: 'lavanta', hint: 'Mor renkli ve güzel kokulu bitki' },
  { category: 'Doğa', answer: 'kelebek', hint: 'Renkli kanatları olan narin böcek' },
  { category: 'Doğa', answer: 'volkan', hint: 'İçinden lav çıkabilen dağ' },
  { category: 'Doğa', answer: 'pusula', hint: 'Yön bulmaya yarayan araç' },
  { category: 'Doğa', answer: 'mağara', hint: 'Kayaların içindeki doğal boşluk' },

  { category: 'Günlük Yaşam', answer: 'macera', hint: 'Heyecan ve keşif dolu yolculuk' },
  { category: 'Günlük Yaşam', answer: 'kahve', hint: 'Çekirdeklerinden sıcak içecek hazırlanır' },
  { category: 'Günlük Yaşam', answer: 'kitap', hint: 'Sayfalarında hikâyeler ve bilgiler taşır' },
  { category: 'Günlük Yaşam', answer: 'pencere', hint: 'Odaya ışık ve hava girmesini sağlar' },
  { category: 'Günlük Yaşam', answer: 'anahtar', hint: 'Kapıyı açıp kilitlemeye yarar' },
  { category: 'Günlük Yaşam', answer: 'valiz', hint: 'Seyahatte eşyaları taşır' },
  { category: 'Günlük Yaşam', answer: 'sandalye', hint: 'Üzerine oturulan mobilya' },
  { category: 'Günlük Yaşam', answer: 'bisiklet', hint: 'Pedalla ilerleyen iki tekerlekli araç' },
  { category: 'Günlük Yaşam', answer: 'şemsiye', hint: 'Yağmurdan korunmak için açılır' },
  { category: 'Günlük Yaşam', answer: 'mutfak', hint: 'Yemeklerin hazırlandığı bölüm' },

  { category: 'Kültür', answer: 'sinema', hint: 'Filmlerin büyük perdede izlendiği sanat' },
  { category: 'Kültür', answer: 'müzik', hint: 'Ritim ve seslerin uyumlu birleşimi' },
  { category: 'Kültür', answer: 'tiyatro', hint: 'Oyuncuların sahnede canlı hikâye anlattığı sanat' },
  { category: 'Kültür', answer: 'resim', hint: 'Renk ve çizgilerle oluşturulan görsel eser' },
  { category: 'Kültür', answer: 'festival', hint: 'Sanat ve eğlenceyi buluşturan büyük etkinlik' },
  { category: 'Kültür', answer: 'bilmece', hint: 'Cevabı düşünerek bulunan kısa soru' },
  { category: 'Kültür', answer: 'masal', hint: 'Olağanüstü olaylarla dolu anlatı' },
  { category: 'Kültür', answer: 'heykel', hint: 'Taş veya metalden yapılan üç boyutlu eser' },
  { category: 'Kültür', answer: 'melodi', hint: 'Akılda kalan düzenli nota dizisi' },
  { category: 'Kültür', answer: 'dans', hint: 'Müziğin ritmine uygun hareketler' },

  { category: 'Meslek', answer: 'öğretmen', hint: 'Bilgiyi öğrencilerine aktaran kişi' },
  { category: 'Meslek', answer: 'mühendis', hint: 'Teknik problemler için çözüm tasarlar' },
  { category: 'Meslek', answer: 'doktor', hint: 'Hastaları muayene edip tedavi eder' },
  { category: 'Meslek', answer: 'avukat', hint: 'Hukuki konularda kişileri temsil eder' },
  { category: 'Meslek', answer: 'mimar', hint: 'Yapıların planını ve görünümünü tasarlar' },
  { category: 'Meslek', answer: 'pilot', hint: 'Uçağı güvenli biçimde kullanan kişi' },
  { category: 'Meslek', answer: 'ressam', hint: 'Renk ve çizgilerle eser üretir' },
  { category: 'Meslek', answer: 'gazeteci', hint: 'Haberleri araştırıp kamuya aktarır' },
  { category: 'Meslek', answer: 'terzi', hint: 'Kumaştan kıyafet diker ve onarır' },
  { category: 'Meslek', answer: 'çiftçi', hint: 'Toprağı işleyerek ürün yetiştirir' },

  { category: 'Şehir', answer: 'başkent', hint: 'Bir ülkenin yönetim merkezidir' },
  { category: 'Şehir', answer: 'meydan', hint: 'Şehirde insanların buluştuğu geniş açık alan' },
  { category: 'Şehir', answer: 'köprü', hint: 'İki yakayı birbirine bağlayan yapı' },
  { category: 'Şehir', answer: 'cadde', hint: 'Şehrin geniş ve işlek yollarından biri' },
  { category: 'Şehir', answer: 'metro', hint: 'Şehir içinde çoğunlukla yer altında ilerler' },
  { category: 'Şehir', answer: 'park', hint: 'Ağaçlar ve yürüyüş yollarıyla dolu dinlenme alanı' },
  { category: 'Şehir', answer: 'müze', hint: 'Tarihî ve sanatsal eserlerin sergilendiği yer' },
  { category: 'Şehir', answer: 'kule', hint: 'Yüksek ve dar biçimli yapı' },
  { category: 'Şehir', answer: 'liman', hint: 'Gemilerin yük ve yolcu aldığı kıyı alanı' },
  { category: 'Şehir', answer: 'çarşı', hint: 'Yan yana dükkânların bulunduğu alışveriş bölgesi' },

  { category: 'Bilim', answer: 'atom', hint: 'Bir elementin kimyasal özelliklerini taşıyan en küçük birim' },
  { category: 'Bilim', answer: 'molekül', hint: 'Birbirine bağlanmış atomlardan oluşur' },
  { category: 'Bilim', answer: 'enerji', hint: 'İş yapabilme yeteneği olarak tanımlanır' },
  { category: 'Bilim', answer: 'yerçekimi', hint: 'Cisimleri Dünya’nın merkezine doğru çeker' },
  { category: 'Bilim', answer: 'deney', hint: 'Bir düşünceyi kontrollü koşullarda sınar' },
  { category: 'Bilim', answer: 'laboratuvar', hint: 'Bilimsel araştırma ve ölçümlerin yapıldığı yer' },
  { category: 'Bilim', answer: 'mikroskop', hint: 'Çok küçük nesneleri büyüterek gösterir' },
  { category: 'Bilim', answer: 'teleskop', hint: 'Uzak gök cisimlerini gözlemlemeyi sağlar' },
  { category: 'Bilim', answer: 'formül', hint: 'Bir ilişkiyi sembollerle kısa biçimde gösterir' },
  { category: 'Bilim', answer: 'element', hint: 'Aynı tür atomlardan oluşan saf madde' },

  { category: 'Ev', answer: 'buzdolabı', hint: 'Yiyecekleri soğuk tutarak korur' },
  { category: 'Ev', answer: 'televizyon', hint: 'Görüntülü yayınların izlendiği cihaz' },
  { category: 'Ev', answer: 'koltuk', hint: 'Rahatça oturmak için kullanılan mobilya' },
  { category: 'Ev', answer: 'masa', hint: 'Üzerinde yemek yenilen veya çalışılan mobilya' },
  { category: 'Ev', answer: 'yastık', hint: 'Uyurken başın altına konur' },
  { category: 'Ev', answer: 'battaniye', hint: 'Soğukta sıcak kalmak için örtülür' },
  { category: 'Ev', answer: 'dolap', hint: 'Eşyaları düzenli biçimde saklar' },
  { category: 'Ev', answer: 'ayna', hint: 'Karşısındaki görüntüyü yansıtır' },
  { category: 'Ev', answer: 'lamba', hint: 'Bulunduğu ortamı aydınlatır' },
  { category: 'Ev', answer: 'balkon', hint: 'Binanın dışarı açılan yüksek bölümü' },

  { category: 'Ulaşım', answer: 'otomobil', hint: 'Karayolunda kullanılan dört tekerlekli araç' },
  { category: 'Ulaşım', answer: 'otobüs', hint: 'Çok sayıda yolcuyu karayolunda taşır' },
  { category: 'Ulaşım', answer: 'tren', hint: 'Rayların üzerinde vagonlarla ilerler' },
  { category: 'Ulaşım', answer: 'uçak', hint: 'Kanatlarıyla gökyüzünde yolcu taşır' },
  { category: 'Ulaşım', answer: 'gemi', hint: 'Denizlerde yük veya yolcu taşır' },
  { category: 'Ulaşım', answer: 'taksi', hint: 'Ücret karşılığında şehir içi yolcu taşır' },
  { category: 'Ulaşım', answer: 'motosiklet', hint: 'Motorla ilerleyen iki tekerlekli taşıt' },
  { category: 'Ulaşım', answer: 'tramvay', hint: 'Şehir caddelerindeki raylarda ilerler' },
  { category: 'Ulaşım', answer: 'feribot', hint: 'İki kıyı arasında araç ve yolcu taşır' },
  { category: 'Ulaşım', answer: 'istasyon', hint: 'Tren ve metro yolcularının inip bindiği yer' },

  { category: 'Duygu', answer: 'mutluluk', hint: 'İnsanın kendini iyi ve huzurlu hissetmesi' },
  { category: 'Duygu', answer: 'heyecan', hint: 'Kalbi hızlandıran güçlü merak ve coşku' },
  { category: 'Duygu', answer: 'merak', hint: 'Bir şeyi öğrenme ve keşfetme isteği' },
  { category: 'Duygu', answer: 'cesaret', hint: 'Korkuya rağmen harekete geçme gücü' },
  { category: 'Duygu', answer: 'sabır', hint: 'Zorluklar karşısında sakin biçimde bekleyebilmek' },
  { category: 'Duygu', answer: 'umut', hint: 'Gelecekte iyi şeyler olacağına duyulan inanç' },
  { category: 'Duygu', answer: 'sevinç', hint: 'Güzel bir olay karşısında duyulan coşku' },
  { category: 'Duygu', answer: 'şaşkınlık', hint: 'Beklenmedik bir olay karşısında hissedilir' },
  { category: 'Duygu', answer: 'özlem', hint: 'Uzakta olan birini veya yeri görme isteği' },
  { category: 'Duygu', answer: 'güven', hint: 'Birine veya bir şeye inanıp dayanma duygusu' },
]

const scrambleWord = (answer: string, index: number) => {
  const letters = [...answer.toLocaleUpperCase('tr-TR')]
  let seed = (index + 1) * 7919
  for (let cursor = letters.length - 1; cursor > 0; cursor -= 1) {
    seed = (seed * 1664525 + 1013904223) >>> 0
    const target = seed % (cursor + 1)
    ;[letters[cursor], letters[target]] = [letters[target], letters[cursor]]
  }
  if (letters.join('').toLocaleLowerCase('tr-TR') === answer.toLocaleLowerCase('tr-TR')) letters.reverse()
  return letters.join(' ')
}

const wordPuzzlesTr = wordBank.map((puzzle, index) => ({
  ...puzzle,
  scrambled: scrambleWord(puzzle.answer, index),
}))

export const wordPuzzles = isEnglish ? englishWordPuzzles : wordPuzzlesTr

export const createInitialSignals = (): GameSignals => ({
  totalMessages: 0,
  uniqueViewers: 0,
  lastActor: null,
  football: { home: 0, away: 0 },
  quiz: [0, 0, 0, 0],
  wheel: {},
  emoji: { attempts: 0, winners: [] },
  word: { attempts: 0, winners: [] },
  numbers: { one: 0, two: 0 },
  tetris: { actionSeq: 0, commands: 0, lastAction: null },
  pickaxe: {
    depth: 0, mined: 0, combo: 0, energy: 0, lane: 3, tnt: 0, megaTnt: 0,
    tier: 'wood', speed: 'normal', bigHits: 0, blockDamage: 0, lastOre: null,
    ores: { coal: 0, copper: 0, iron: 0, gold: 0, crystal: 0, emerald: 0 },
    lastGain: 0, lastAction: null,
  },
  raid: { damage: 0, hits: 0, lastDamage: 0, communityHp: 250, heals: 0, healing: 0, lastHeal: 0, bossAttacks: 0, lastBossDamage: 0, lastAction: null },
})
